apiVersion: v2
name: gha-runner-scale-set
description: Github Actions Runner Scale Set
type: application

version: 1.0.0

dependencies:
  - name: gha-runner-scale-set
    version: "0.13.0"
    repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
