apiVersion: v2
name: gha-runner-scale-set-controller
description: Github Actions Runner Scale Set Controller
type: application

version: 1.0.0

dependencies:
  - name: gha-runner-scale-set-controller
    version: "0.13.0"
    repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
