apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/part-of: webserver
  app.kubernetes.io/managed-by: argocd
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - ingress.yaml
