apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: deluge.pynenborg.com
      http:
        paths:
          - backend:
              service:
                name: deluge
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - deluge.pynenborg.com
      secretName: deluge-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge-ts
spec:
  defaultBackend:
    service:
      name: deluge
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - deluge
