resources:
  - arc.yaml
  - authentik.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - local-path-provisioner.yaml
  - media.yaml
  - metallb.yaml
  - pihole.yaml
  - postgres.yaml
  - tailscale.yaml
  - traefik.yaml
