apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: celpynenborg@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector: { }
        dns01:
          route53:
            region: eu-west-1
            accessKeyIDSecretRef:
              name: aws-credentials
              key: accessKeyId
            secretAccessKeySecretRef:
              name: aws-credentials
              key: secretAccessKey
