apiVersion: v2
name: github-actions
description: Github Actions Runner Scale Set Controller and Scale Set
type: application

version: 1.0.0

dependencies:
  - name: gha-runner-scale-set-controller
    version: "0.12.1"
    repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
  - name: gha-runner-scale-set
    version: "0.12.1"
    repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
