apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/workloads/arc
    repoURL: 'git@github.com:CelPyn/infra.git'
    targetRevision: HEAD
    helm:
      releaseName: github-actions
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc
