apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-infra
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/infrastructure/argocd
    repoURL: 'git@github.com:CelPyn/infra.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
