apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnamicharts/external-dns
    repoURL: registry-1.docker.io
    targetRevision: 8.3.5
    helm:
      releaseName: external-dns
      values: |
        txtOwnerId: cel
        domainFilters:
          - pynenborg.com
        policy: sync
        env:
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /etc/aws/credentials/credentials
        extraVolumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials
        extraVolumeMounts:
          - name: aws-credentials
            mountPath: /etc/aws/credentials
            readOnly: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
