apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.5
    helm:
      releaseName: external-dns
      values: |
        txtOwnerId: cel
        domainFilters:
          - pynenborg.com
        env:
          - name: AWS_DEFAULT_REGION
            value: eu-west-1
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /etc/aws/credentials/credentials
        extraVolumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials
        extraVolumeMounts:
          - name: aws-credentials
            mountPath: /etc/aws/credentials
            readOnly: true
        provider:
          name: aws
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
