apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 7.0.2
    helm:
      values: |
        tty: true
        
        customRules:
          10-exceptions.yaml: |
            - rule: Drop and execute new binary in container
              override:
                exceptions: append
              exceptions:
                - name: allow_chromedriver_in_flaresolverr
                  fields: [container.name, proc.name, k8s.ns.name]
                  comps: [=, =, =]
                  values: 
                    - [flaresolverr, chromedriver, media]
        
        falcosidekick:
          enabled: true
          config:
            extraEnv:
                - name: TELEGRAM_TOKEN
                  valueFrom:
                    secretKeyRef:
                        name: telegram-credentials
                        key: token
                - name: TELEGRAM_CHATID
                  valueFrom:
                    secretKeyRef:
                        name: telegram-credentials
                        key: chat-id
            telegram:
              minimumpriority: warning
      releaseName: falco
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
