apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 7.0.2
    helm:
      values: |
        tty: true
        
        falcosidekick:
          enabled: true
          config:
            extraEnv:
                - name: TELEGRAM_TOKEN
                  valueFrom:
                    secretKeyRef:
                        name: telegram-credentials
                        key: token
                - name: TELEGRAM_CHATID
                  valueFrom:
                    secretKeyRef:
                        name: telegram-credentials
                        key: chat-id
            telegram:
              minimumpriority: warning
      releaseName: falco
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
