resources:
  - alloy.yaml
  - argocd.yaml
  - authentik.yaml
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - external-dns.yaml
  - local-path-provisioner.yaml
  - media
  - metallb.yaml
  - namespaces.yaml
#  - pihole.yaml
  - postgres-databases.yaml
  - prometheus-node-exporter.yaml
  - prometheus-operator-crds.yaml
  - storage.yaml
  - tailscale.yaml
  - traefik.yaml

patches:
  - target:
      kind: Application
    path: patches/argocd-finalizers.yaml
  - target:
      kind: Application
    path: patches/argocd-sync-policy.yaml
