resources:
  - namespaces.yaml
  - traefik.yaml
  - metallb.yaml
patches:
  - target:
      kind: Application
    path: patches/argocd-finalizers.yaml
  - target:
      kind: Application
    path: patches/argocd-sync-policy.yaml
