resources:
  - argocd.yaml
  - cert-manager.yaml
#  - external-dns.yaml
  - metallb.yaml
  - namespaces.yaml
  - traefik.yaml

patches:
  - target:
      kind: Application
    path: patches/argocd-finalizers.yaml
  - target:
      kind: Application
    path: patches/argocd-sync-policy.yaml
