apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.3
    helm:
      releaseName: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-infra
spec:
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/infrastructure/metallb
    repoURL: 'git@github.com:CelPyn/infra.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
