---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-databases
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/infrastructure/postgres
    repoURL: 'git@github.com:CelPyn/infra.git'
    targetRevision: HEAD
  project: default
