apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.49.2
    helm:
      releaseName: prometheus-node-exporter
      values: |
        prometheus:
          monitor:
            enabled: true
            relabelings:              
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: hostname
                action: replace
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - Recreate=false
