apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 20.0.0
    helm:
      releaseName: prometheus-operator-crds
      values: |
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
