apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  destination:
    namespace: media
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/infrastructure/storage
    repoURL: 'git@github.com:CelPyn/infra.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
