apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.90.9
    helm:
      releaseName: tailscale-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
