on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 1'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Run Renovate
        uses: renovatebot/github-action@v44.0.0
        with:
          config-file: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
